apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: acmecontrollers.acme.openshift.io
spec:
  group: acme.openshift.io
  names:
    kind: ACMEController
    plural: acmecontrollers
    singular: acmecontroller
  scope: Cluster
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    "schema":
      "openAPIV3Schema":
        description: ACMEController provides information to configure an operator
          to manage openshift-acme controller.
        type: object
        required:
        - spec
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: spec is the specification of the desired behavior of the
              openshift-acme controller
            type: object
            properties:
              logLevel:
                description: logLevel is an intent based logging for an overall component.  It
                  does not give fine grained control, but it is a simple way to manage
                  coarse grained logging choices that operators have to interpret
                  for their operands.
                type: string
              managementState:
                description: managementState indicates whether and how the operator
                  should manage the component
                type: string
                pattern: ^(Managed|Unmanaged|Force|Removed)$
              operatorLogLevel:
                description: operatorLogLevel is an intent based logging for the operator
                  itself.  It does not give fine grained control, but it is a simple
                  way to manage coarse grained logging choices that operators have
                  to interpret for themselves.
                type: string
          status:
            description: status is the most recently observed status of the openshift-acme
              controller
            type: object
            properties:
              availableReplicas:
                description: availableReplicas indicates how many replicas are available
                  and at the desired state
                type: integer
                format: int32
              conditions:
                description: conditions is a list of conditions and their status
                type: array
                items:
                  description: OperatorCondition is just the standard condition fields.
                  type: object
                  properties:
                    lastTransitionTime:
                      type: string
                      format: date-time
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
              observedGeneration:
                description: observedGeneration is the last generation change you've
                  dealt with
                type: integer
                format: int64
              version:
                description: version is the level this availability applies to
                type: string
