apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-acme
roleRef:
  kind: ClusterRole
  name: openshift-acme
subjects:
- kind: ServiceAccount
  namespace: acme-controller
  name: openshift-acme
