apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-acme
roleRef:
  kind: Role
  name: openshift-acme
subjects:
- kind: ServiceAccount
  name: openshift-acme
